Repository squad-map/squad-map-project, pull requests merged in 2022-11, with the labels that each got.

#130 [BE] 멤버 및 지도 검색 API
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/com/squadmap/category/application/dto/CategoryInfo.java
  BE/src/main/java/com/squadmap/common/AuthInterceptor.java
  BE/src/main/java/com/squadmap/common/SimplePage.java
  BE/src/main/java/com/squadmap/common/auth/LoginArgumentResolver.java
  BE/src/main/java/com/squadmap/common/auth/application/GithubProvider.java
  BE/src/main/java/com/squadmap/common/auth/application/JwtProvider.java
  BE/src/main/java/com/squadmap/common/auth/application/LoginService.java
  BE/src/main/java/com/squadmap/common/auth/application/NaverProvider.java
  BE/src/main/java/com/squadmap/common/auth/application/OauthProvider.java
  BE/src/main/java/com/squadmap/common/auth/application/OauthService.java
  BE/src/main/java/com/squadmap/common/auth/application/dto/github/GithubEmail.java
  BE/src/main/java/com/squadmap/common/config/httpClientConfig.java
  BE/src/main/java/com/squadmap/map/application/MapService.java
  BE/src/main/java/com/squadmap/map/application/MapServiceImpl.java
  BE/src/main/java/com/squadmap/map/application/dto/MapDetail.java
  BE/src/main/java/com/squadmap/map/application/dto/MapSimpleInfo.java
  BE/src/main/java/com/squadmap/map/domain/Map.java
  BE/src/main/java/com/squadmap/map/infrastructure/MapRepository.java
  BE/src/main/java/com/squadmap/map/ui/MapController.java
  BE/src/main/java/com/squadmap/map/ui/dto/MapRequest.java
  BE/src/main/java/com/squadmap/member/application/MemberService.java
  BE/src/main/java/com/squadmap/member/application/MemberServiceImpl.java
  BE/src/main/java/com/squadmap/member/application/dto/MemberSimpleInfo.java
  BE/src/main/java/com/squadmap/member/infrastructure/MemberRepository.java
  BE/src/main/java/com/squadmap/member/ui/MemberController.java
  BE/src/main/java/com/squadmap/member/ui/dto/NicknameUpdateResponse.java
  BE/src/main/java/com/squadmap/place/application/PlaceService.java
  BE/src/main/java/com/squadmap/place/application/PlaceServiceImpl.java
  BE/src/main/java/com/squadmap/place/application/dto/PlaceDetailInfo.java
  BE/src/main/java/com/squadmap/place/application/dto/PlaceSimpleInfo.java
  BE/src/main/java/com/squadmap/place/domain/Position.java
  BE/src/main/java/com/squadmap/place/ui/PlaceController.java
  BE/src/main/java/com/squadmap/place/ui/dto/PlaceRequest.java
  BE/src/main/java/com/squadmap/place/ui/dto/PlaceUpdateRequest.java
  BE/src/main/java/com/squadmap/place/ui/dto/Point.java
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/com/squadmap/assured/RestAssuredTest.java
  BE/src/test/java/com/squadmap/auth/acceptance/OauthAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java
  BE/src/test/java/com/squadmap/group/acceptance/GroupMemberAcceptanceTest.java
  BE/src/test/java/com/squadmap/group/integretion/GroupServiceTest.java
  BE/src/test/java/com/squadmap/map/acceptance/MapAcceptanceTest.java
  BE/src/test/java/com/squadmap/map/integration/MapServiceTest.java
  BE/src/test/java/com/squadmap/member/acceptance/MemberAcceptanceTest.java
  BE/src/test/java/com/squadmap/member/integration/MemberServiceTest.java
  BE/src/test/java/com/squadmap/place/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/com/squadmap/place/integration/PlaceServiceTest.java
Labels: BE

#135 🚧 카테고리 생성 및 조회 기능 구현
  FE/src/apis/category.ts
  FE/src/components/Category/CategoryModalInfo.style.ts
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/types/category.ts
Labels: feature, FE

#137 ♻️ 비로그인시에 로그인이 필요한 페이지에 접근시 로그인페이지로 리다이렉트 시키기. (로그인 페이지는 차후에 다시 재디자인)
  FE/src/App.tsx
  FE/src/hooks/UseLogin.ts
  FE/src/pages/Login/index.tsx
  FE/src/pages/Verification.tsx
Labels: FE, refactor

#138 ♻️ 그룹 관련 기능 구현 진행전에 컴포넌트 css 수정, 데이터 서버와 동기화
  FE/src/components/common/Header/Navigation/index.tsx
  FE/src/pages/MyPage/Item/Item.style.ts
  FE/src/pages/MyPage/Item/index.tsx
  FE/src/pages/SearchMap/PlaceInfos/index.tsx
Labels: FE, refactor

#141 ♻️ FE-refactor : 서버 api 수정 => 클라이언트쪽도 맞춰주기
  FE/src/apis/mypage.ts
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/common/GlobalModal/index.tsx
  FE/src/pages/MapForm/Form/index.tsx
  FE/src/pages/MyPage/index.tsx
  FE/src/pages/SearchMap/ModalContent/index.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/types/map.ts
Labels: FE, refactor

#146 ♻️ FE: 최근검색어 관련 부분 타입 명시적 으로 수정
  FE/src/components/RecentSearch/index.tsx
  FE/src/pages/SearchMap/SearchPlace/index.tsx
  FE/src/recoil/atoms/searchplace.ts
Labels: FE, refactor

#148 🚧 FE: 그룹 관리 인풋 키보드 이벤트 관련 기능 작업 진행, 해당 지도의 그룹 멤버들 가져와서 뿌려주기
  FE/src/apis/group.ts
  FE/src/constants/key.ts
  FE/src/pages/MyPage/Authority/Authority.style.ts
  FE/src/pages/MyPage/Authority/GroupInfo/GroupInfo.style.ts
  FE/src/pages/MyPage/Authority/GroupInfo/index.tsx
  FE/src/pages/MyPage/Authority/index.tsx
  FE/src/pages/MyPage/Item/index.tsx
Labels: feature, FE, refactor

#149 🚧 FE: 나의지도 - 그룹 멤버 관련 컴포넌트 분리 & 그룹 멤버 추가 완료 => 이미 등록된 멤버를 또 등록될 시 처리 필요.
  FE/src/apis/group.ts
  FE/src/pages/MyPage/Authority/Authority.style.ts
  FE/src/pages/MyPage/Authority/GroupInfo/GroupInfo.style.ts
  FE/src/pages/MyPage/Authority/SearchContent/SearchContent.style.ts
  FE/src/pages/MyPage/Authority/SearchContent/index.tsx
  FE/src/pages/MyPage/Authority/SearchForm/SearchForm.style.ts
  FE/src/pages/MyPage/Authority/SearchForm/index.tsx
  FE/src/pages/MyPage/Authority/SearchSubmitButton/SearchSubmitButton.style.ts
  FE/src/pages/MyPage/Authority/SearchSubmitButton/index.tsx
  FE/src/pages/MyPage/Authority/index.tsx
  FE/src/types/group.ts
Labels: feature, FE

#151 🚧 FE: Alert용 Popup Component 구현
  FE/src/components/common/GlobalModal/GlobalModal.style.ts
  FE/src/components/common/Popup/Popup.style.ts
  FE/src/components/common/Popup/index.tsx
Labels: feature, FE

#152 🚧♻️ : FE : 그룹관련하여 추가, 수정, 삭제 기능 구현 & Authority pages 밑에서 관리하는 부분들 컴포넌트 분리
  FE/src/apis/group.ts
  FE/src/components/Authority/GroupInfo/GroupInfo.style.ts
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Authority/SearchForm/SearchForm.style.ts
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Authority/SearchSubmitButton/SearchSubmitButton.style.ts
  FE/src/components/Authority/SearchSubmitButton/index.tsx
  FE/src/pages/MyPage/Authority/GroupInfo/index.tsx
  FE/src/pages/MyPage/Authority/SearchContent/SearchContent.style.ts
  FE/src/pages/MyPage/Authority/SearchContent/index.tsx
  FE/src/pages/MyPage/Authority/SearchSubmitButton/SearchSubmitButton.style.ts
  FE/src/pages/MyPage/Authority/index.tsx
  FE/src/pages/MyPage/Item/index.tsx
Labels: feature, FE, refactor

#153 [BE] 테스트 격리 및 TestContainer 적용
  BE/build.gradle
  BE/src/main/java/com/squadmap/category/application/CategoryServiceImpl.java
  BE/src/main/java/com/squadmap/category/domain/Category.java
  BE/src/main/java/com/squadmap/category/ui/CategoryController.java
  BE/src/main/java/com/squadmap/comment/domain/Comment.java
  BE/src/main/java/com/squadmap/common/AuthInterceptor.java
  BE/src/main/java/com/squadmap/common/excetpion/GlobalExceptionHandler.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/com/squadmap/DbConfigurator.java
  BE/src/test/java/com/squadmap/IntegrationTest.java
  BE/src/test/java/com/squadmap/IsolationTestExecutionListener.java
  BE/src/test/java/com/squadmap/SquadmapApplicationTests.java
  BE/src/test/java/com/squadmap/assured/RestAssuredTest.java
  BE/src/test/java/com/squadmap/auth/acceptance/OauthAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/acceptance/CategoryAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java
  BE/src/test/java/com/squadmap/comment/integration/CommentServiceTest.java
  BE/src/test/java/com/squadmap/group/acceptance/GroupMemberAcceptanceTest.java
  BE/src/test/java/com/squadmap/group/integretion/GroupServiceTest.java
  BE/src/test/java/com/squadmap/map/integration/MapServiceTest.java
  BE/src/test/java/com/squadmap/member/acceptance/MemberAcceptanceTest.java
  BE/src/test/java/com/squadmap/member/integration/MemberServiceTest.java
  BE/src/test/java/com/squadmap/place/integration/PlaceServiceTest.java
  BE/src/test/resources/application-test.yml
  BE/src/test/resources/data-script.sql
  BE/src/test/resources/test-auth.yml
Labels: BE

#154 [BE] 댓글 기능 구현
  BE/src/main/java/com/squadmap/comment/application/CommentService.java
  BE/src/main/java/com/squadmap/comment/application/CommentServiceImpl.java
  BE/src/main/java/com/squadmap/comment/application/dto/CommentInfo.java
  BE/src/main/java/com/squadmap/comment/application/dto/CommentResponse.java
  BE/src/main/java/com/squadmap/comment/domain/Comment.java
  BE/src/main/java/com/squadmap/comment/infrastructure/CommentRepository.java
  BE/src/main/java/com/squadmap/comment/ui/CommentController.java
  BE/src/main/java/com/squadmap/comment/ui/dto/CommentRequest.java
  BE/src/main/java/com/squadmap/common/SimpleSlice.java
  BE/src/main/java/com/squadmap/common/excetpion/ErrorStatusCodeAndMessage.java
  BE/src/main/java/com/squadmap/place/application/PlaceServiceImpl.java
  BE/src/main/java/com/squadmap/place/application/dto/PlaceDetailInfo.java
  BE/src/main/java/com/squadmap/place/infrastructure/PlaceRepository.java
  BE/src/test/java/com/squadmap/assured/RestAssuredTest.java
  BE/src/test/java/com/squadmap/comment/acceptance/CommentAcceptanceTest.java
  BE/src/test/java/com/squadmap/comment/domain/CommentTest.java
  BE/src/test/java/com/squadmap/comment/integration/CommentServiceTest.java
  BE/src/test/java/com/squadmap/place/acceptance/PlaceAcceptanceTest.java
  BE/src/test/resources/application-test.yml
  BE/src/test/resources/data-script.sql
Labels: BE
