Repository squad-map/squad-map-project, pull requests merged in 2022-08, with the labels that each got.

#7 Fe setting/settings
  FE/.babelrc
  FE/.eslintrc.js
  FE/.gitignore
  FE/.prettierrc.js
  FE/.storybook/main.js
  FE/.storybook/preview.js
  FE/config/webpack.common.js
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/mockServiceWorker.js
  FE/src/App.tsx
  FE/src/components/common/Button/Button.stories.tsx
  FE/src/components/common/Button/Button.style.ts
  FE/src/components/common/Button/Button.test.tsx
  FE/src/components/common/Button/index.tsx
  FE/src/index.tsx
  FE/src/mocks/browsers/index.js
  FE/src/mocks/handlers/index.js
  FE/src/pages/AllMapsPage.tsx
  FE/src/pages/style.ts
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/mixin.ts
  FE/src/styles/reset.css
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
  FE/src/types/global.d.ts
  FE/tsconfig.json
Labels: FE

#9 [FE] Jest setup
  FE/package.json
  FE/src/styles/theme.ts
  FE/yarn.lock
Labels: FE

#12 [Android] #11 bottom navigation 구현
  Android/.gitignore
  Android/.gitkeep
  Android/.idea/.gitignore
  Android/.idea/.name
  Android/.idea/compiler.xml
  Android/.idea/gradle.xml
  Android/.idea/misc.xml
  Android/.idea/vcs.xml
  Android/app/.gitignore
  Android/app/build.gradle
  Android/app/proguard-rules.pro
  Android/app/src/androidTest/java/com/example/squadmap/ExampleInstrumentedTest.kt
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/squadmap/data/model/AllMap.kt
  Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt
  Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavMenu.kt
  Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/category/CategoryScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/login/LoginScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/mymap/MyMapScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/profile/ProfileScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/theme/Color.kt
  Android/app/src/main/java/com/example/squadmap/ui/theme/Shape.kt
  Android/app/src/main/java/com/example/squadmap/ui/theme/Theme.kt
  Android/app/src/main/java/com/example/squadmap/ui/theme/Type.kt
  Android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android/app/src/main/res/drawable/ic_category.xml
  Android/app/src/main/res/drawable/ic_home.xml
  Android/app/src/main/res/drawable/ic_launcher_background.xml
  Android/app/src/main/res/drawable/ic_my_map.xml
  Android/app/src/main/res/drawable/ic_profile.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/themes.xml
  Android/app/src/main/res/xml/backup_rules.xml
  Android/app/src/main/res/xml/data_extraction_rules.xml
  Android/app/src/test/java/com/example/squadmap/ExampleUnitTest.kt
  Android/build.gradle
  Android/gradle.properties
  Android/gradle/wrapper/gradle-wrapper.jar
  Android/gradle/wrapper/gradle-wrapper.properties
  Android/gradlew
  Android/gradlew.bat
  Android/settings.gradle
  README.md
Labels: Android

#15 [Android] FEAT: Search 화면 생성과 연결
  Android/.idea/misc.xml
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/search/SearchScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/utils/SquadMapIcons.kt
Labels: Android

#19 [FE] 홈 관련 브랜치 Update 하기 위한 PR
  FE/src/components/common/LoadingSpinner/LoadingSpinner.stories.tsx
  FE/src/components/common/LoadingSpinner/LoadingSpinner.style.ts
  FE/src/components/common/LoadingSpinner/index.tsx
Labels: FE

#20 [FE] Navigation, Header Component CSS 조정
  FE/src/components/GridCards/GridCards.style.ts
  FE/src/components/common/Header/Header.style.ts
  FE/src/components/common/Header/Navigation/Navigation.style.ts
  FE/src/pages/Home/Home.style.ts
  FE/src/styles/GlobalStyle.tsx
Labels: FE

#23 [FE] Component 수정
  FE/src/components/GridCards/GridCards.stories.tsx
  FE/src/components/GridCards/GridCards.style.ts
  FE/src/components/GridCards/index.tsx
  FE/src/components/common/Card/Card.style.ts
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Text/Text.style.ts
Labels: FE

#25 [FE] component to Home branch merge
  FE/src/components/GridCards/GridCards.stories.tsx
  FE/src/components/GridCards/GridCards.style.ts
  FE/src/components/GridCards/index.tsx
  FE/src/components/common/Card/Card.style.ts
  FE/src/components/common/Header/Header.style.ts
  FE/src/components/common/Header/Navigation/Navigation.style.ts
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Text/Text.style.ts
  FE/src/pages/Home/Home.style.ts
  FE/src/styles/GlobalStyle.tsx
Labels: FE

#27 [FE] MyPage Component 기능 작업
  FE/src/assets/icons/edit.svg
  FE/src/assets/icons/index.ts
  FE/src/constants/dummyData.js
  FE/src/interfaces/IMyMap.ts
  FE/src/mocks/handlers/index.js
  FE/src/pages/MyPage/Item/Item.stories.tsx
  FE/src/pages/MyPage/Item/Item.style.ts
  FE/src/pages/MyPage/Item/index.tsx
  FE/src/pages/MyPage/MyPage.stories.tsx
  FE/src/pages/MyPage/MyPage.style.ts
  FE/src/pages/MyPage/index.tsx
  FE/src/types/map.ts
Labels: feature, FE

#28 [FE] Home Component msw 연동, 링크 컴포넌트 추가 하여 카드 링크 연결
  FE/src/pages/Home/Home.stories.tsx
  FE/src/pages/Home/index.tsx
Labels: FE
