Repository squad-map/squad-map-project, pull requests merged in 2022-12, with the labels that each got.

#156 [BE] 미비 TEST 추가
  BE/src/main/java/com/squadmap/common/auth/AuthInterceptor.java
  BE/src/main/java/com/squadmap/common/config/WebConfig.java
  BE/src/main/java/com/squadmap/common/config/httpClientConfig.java
  BE/src/main/java/com/squadmap/common/excetpion/ErrorStatusCodeAndMessage.java
  BE/src/main/java/com/squadmap/core/category/application/CategoryServiceImpl.java
  BE/src/main/java/com/squadmap/core/category/domain/Category.java
  BE/src/main/java/com/squadmap/core/category/infrastructure/CategoryRepository.java
  BE/src/main/java/com/squadmap/core/group/application/GroupMemberServiceImpl.java
  BE/src/main/java/com/squadmap/core/group/domain/GroupMember.java
  BE/src/main/java/com/squadmap/core/group/domain/PermissionLevel.java
  BE/src/main/java/com/squadmap/core/place/application/PlaceServiceImpl.java
  BE/src/main/java/com/squadmap/member/domain/Member.java
  BE/src/main/java/com/squadmap/member/ui/dto/NicknameUpdateRequest.java
  BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java
  BE/src/test/java/com/squadmap/comment/integration/CommentServiceTest.java
  BE/src/test/java/com/squadmap/group/integretion/GroupServiceTest.java
  BE/src/test/java/com/squadmap/map/integration/MapServiceTest.java
  BE/src/test/java/com/squadmap/member/integration/MemberServiceTest.java
  BE/src/test/java/com/squadmap/place/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/com/squadmap/place/integration/PlaceServiceTest.java
  BE/src/test/resources/data-script.sql
Labels: BE, test

#159 ♻️ KaKao Map API 요청 후 응답받는 데이터 키 place_name 으로 수정
  FE/src/components/KaKaoMap/index.tsx
  FE/src/pages/Map/Infos/index.tsx
  FE/src/pages/SearchMap/ModalContent/index.tsx
  FE/src/pages/SearchMap/PlaceInfos/index.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/types/map.ts
Labels: FE, refactor

#161 Fe refactor/tailwind update merge to FE
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Header/Navigation/index.tsx
  FE/src/interfaces/IMyMap.ts
  FE/src/interfaces/Place.ts
  FE/src/pages/Map/Infos/Infos.style.ts
  FE/src/pages/Map/Infos/index.tsx
  FE/src/pages/Map/Map.style.ts
  FE/src/pages/Map/PlaceModalContent/ModalContent.stories.tsx
  FE/src/pages/Map/PlaceModalContent/ModalContent.style.ts
  FE/src/pages/Map/PlaceModalContent/index.tsx
  FE/src/pages/Map/PlaceModalReview/ModalContent.style.ts
  FE/src/pages/Map/PlaceModalReview/index.tsx
  FE/src/pages/Map/PlaceModalUpdate/index.tsx
  FE/src/pages/Map/index.tsx
  FE/src/pages/MyPage/Item/Item.style.ts
  FE/src/pages/MyPage/Item/index.tsx
  FE/src/pages/SearchMap/ModalContent/index.tsx
Labels: feature, refactor

#162 🚧 FE : 맵 지도 조회 후 카드 데이터에 UserProfile 컴포넌트 추가시키기, 장소 수정 컴포넌트 CSS 수정
  FE/src/interfaces/IMap.ts
  FE/src/pages/Map/Infos/UserProfile.tsx
  FE/src/pages/Map/Infos/index.tsx
  FE/src/pages/Map/PlaceModalUpdate/index.tsx
  FE/src/pages/Map/index.tsx
  FE/src/pages/MyPage/Item/index.tsx
  FE/src/types/map.ts
Labels: feature, FE, refactor

#163 🚧 FE: 맵에 등록된 카테고리 조회 기능 API 도착이전에 우선 제작, 카테고리 생성 기능 완료, 장소 생성 기능도 카테고…
  FE/src/apis/category.ts
  FE/src/components/Category/CategoryModalInfo.style.ts
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/ModalContent/index.tsx
  FE/src/components/common/GlobalModal/GlobalModal.style.ts
  FE/src/components/common/GlobalModal/index.tsx
  FE/src/components/common/Text/index.tsx
  FE/src/pages/Map/Header/Header.style.ts
  FE/src/pages/Map/Header/index.tsx
  FE/src/pages/Map/PlaceModalContent/ModalContent.style.ts
  FE/src/pages/Map/PlaceModalContent/index.tsx
  FE/src/pages/Map/index.tsx
  FE/src/pages/SearchMap/ModalContent/ModalContent.style.ts
  FE/src/pages/SearchMap/ModalContent/index.tsx
  FE/src/pages/SearchMap/PlaceInfos/index.tsx
  FE/src/pages/SearchMap/SearchModalContent/SearchModalContent.stories.tsx
  FE/src/pages/SearchMap/SearchModalContent/index.tsx
  FE/src/types/map.ts
Labels: feature, FE, refactor

#165 🛠 FE: tailwind & storybook 작업 이전에 여러가지 셋팅, 불필요한 파일 삭제
  FE/.babelrc
  FE/.eslintrc.js
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/images/404.png
  FE/src/assets/images/index.ts
  FE/src/constants/dummyData.js
  FE/tailwind.config.js
  FE/yarn.lock
Labels: refactor

#168 [BE] delete 로직 추가
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/com/squadmap/common/auth/application/GithubProvider.java
  BE/src/main/java/com/squadmap/common/auth/application/NaverProvider.java
  BE/src/main/java/com/squadmap/common/config/CacheConfig.java
  BE/src/main/java/com/squadmap/common/config/RedisConfig.java
  BE/src/main/java/com/squadmap/common/dto/CommonResponse.java
  BE/src/main/java/com/squadmap/common/dto/SimplePage.java
  BE/src/main/java/com/squadmap/common/dto/SimpleSlice.java
  BE/src/main/java/com/squadmap/common/dto/SuccessCode.java
  BE/src/main/java/com/squadmap/common/excetpion/ErrorStatusCodeAndMessage.java
  BE/src/main/java/com/squadmap/core/access/AccessAspect.java
  BE/src/main/java/com/squadmap/core/category/application/CategoryService.java
  BE/src/main/java/com/squadmap/core/category/application/CategoryServiceImpl.java
  BE/src/main/java/com/squadmap/core/category/infrastructure/CategoryRepository.java
  BE/src/main/java/com/squadmap/core/category/ui/CategoryController.java
  BE/src/main/java/com/squadmap/core/category/ui/dto/CategoryRequest.java
  BE/src/main/java/com/squadmap/core/category/ui/dto/CategoryUpdateRequest.java
  BE/src/main/java/com/squadmap/core/comment/application/CommentService.java
  BE/src/main/java/com/squadmap/core/comment/application/CommentServiceImpl.java
  BE/src/main/java/com/squadmap/core/comment/infrastructure/CommentRepository.java
  BE/src/main/java/com/squadmap/core/comment/ui/CommentController.java
  BE/src/main/java/com/squadmap/core/group/application/GroupMemberService.java
  BE/src/main/java/com/squadmap/core/group/application/GroupMemberServiceImpl.java
  BE/src/main/java/com/squadmap/core/group/application/dto/GroupMemberInfo.java
  BE/src/main/java/com/squadmap/core/group/infrastructure/GroupMemberRepository.java
  BE/src/main/java/com/squadmap/core/group/ui/GroupMemberController.java
  BE/src/main/java/com/squadmap/core/group/ui/dto/GroupMemberDeleteRequest.java
  BE/src/main/java/com/squadmap/core/map/application/MapService.java
  BE/src/main/java/com/squadmap/core/map/application/MapServiceImpl.java
  BE/src/main/java/com/squadmap/core/map/infrastructure/MapRepository.java
  BE/src/main/java/com/squadmap/core/map/ui/MapController.java
  BE/src/main/java/com/squadmap/core/place/application/PlaceService.java
  BE/src/main/java/com/squadmap/core/place/application/PlaceServiceImpl.java
  BE/src/main/java/com/squadmap/core/place/application/dto/PlaceDetailInfo.java
  BE/src/main/java/com/squadmap/core/place/domain/Place.java
  BE/src/main/java/com/squadmap/core/place/infrastructure/PlaceRepository.java
  BE/src/main/java/com/squadmap/core/place/ui/PlaceController.java
  BE/src/main/java/com/squadmap/member/ui/MemberController.java
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/com/squadmap/IsolationTestExecutionListener.java
  BE/src/test/java/com/squadmap/assured/RestAssuredTest.java
  BE/src/test/java/com/squadmap/auth/acceptance/OauthAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/acceptance/CategoryAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java
  BE/src/test/java/com/squadmap/comment/acceptance/CommentAcceptanceTest.java
  BE/src/test/java/com/squadmap/comment/domain/CommentTest.java
  BE/src/test/java/com/squadmap/group/acceptance/GroupMemberAcceptanceTest.java
  BE/src/test/java/com/squadmap/group/integretion/GroupServiceTest.java
  BE/src/test/java/com/squadmap/map/acceptance/MapAcceptanceTest.java
  BE/src/test/java/com/squadmap/map/integration/MapServiceTest.java
  BE/src/test/java/com/squadmap/member/acceptance/MemberAcceptanceTest.java
  BE/src/test/java/com/squadmap/member/integration/MemberServiceTest.java
  BE/src/test/java/com/squadmap/place/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/com/squadmap/place/integration/PlaceServiceTest.java
Labels: feature, BE
