Repository squad-map/squad-map-project, pull requests merged in 2022-09, with the labels that each got.

#35 [FE] create Page 작업한(70%완료)거 커밋.
  FE/src/apis/mypage.ts
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/minus.svg
  FE/src/assets/images/index.ts
  FE/src/assets/images/plusEmail.svg
  FE/src/components/common/Button/index.tsx
  FE/src/pages/MyPage/Form/EmailBox.tsx
  FE/src/pages/MyPage/Form/Form.stories.tsx
  FE/src/pages/MyPage/Form/Form.style.ts
  FE/src/pages/MyPage/Form/index.tsx
  FE/src/pages/MyPage/Item/index.tsx
  FE/src/pages/MyPage/index.tsx
  FE/src/types/mypage.ts
Labels: feature, FE

#36 [FE] category 임의 컬러 적용해보기
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/filter.css
Labels: FE

#37 [FE] 지금까지 작업한 MyMap Component commit
  FE/.gitignore
  FE/config/webpack.common.js
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/assets/icons/arrowBack.svg
  FE/src/assets/icons/index.ts
  FE/src/components/common/GlobalModal/GlobalModal.stories.tsx
  FE/src/components/common/GlobalModal/GlobalModal.style.ts
  FE/src/components/common/GlobalModal/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/constants/dummyData.js
  FE/src/constants/map.ts
  FE/src/mocks/handlers/index.js
  FE/src/mocks/handlers/mymap.js
  FE/src/mocks/handlers/mypage.js
  FE/src/pages/MyMap/Header/Header.style.ts
  FE/src/pages/MyMap/Header/index.tsx
  FE/src/pages/MyMap/Infos/Infos.style.ts
  FE/src/pages/MyMap/Infos/index.tsx
  FE/src/pages/MyMap/Modal/Modal.stories.tsx
  FE/src/pages/MyMap/Modal/index.tsx
  FE/src/pages/MyMap/MyMap.stories.tsx
  FE/src/pages/MyMap/MyMap.style.ts
  FE/src/pages/MyMap/index.tsx
  FE/src/pages/MyPage/index.tsx
  FE/src/types/map.ts
  FE/yarn.lock
Labels: feature, FE

#38 [FE] MyMap Naver Map API marker & infoWindow 구현 진행
  FE/src/pages/MyMap/index.tsx
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/map.css
Labels: feature, FE

#39 [FE] Refactor => MyPage Component formType 에따라 create, modify 분리
  FE/src/App.tsx
  FE/src/pages/MyPage/Form/index.tsx
  FE/src/pages/MyPage/MyPage.style.ts
  FE/src/pages/MyPage/index.tsx
Labels: feature, FE

#50 [FE] 글로벌 모달 Overlay 약간 수정
  FE/src/components/common/GlobalModal/index.tsx
  FE/src/components/common/Overlay/index.tsx
Labels: FE

#52 [Android] FEAT: 비 로그인 상태로 프로필, 나의 지도 탭으로 이동시 로그인 화면으로 이동
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/squadmap/SquadMapApp.kt
  Android/app/src/main/java/com/example/squadmap/common/AppSession.kt
  Android/app/src/main/java/com/example/squadmap/data/model/JWT.kt
  Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt
  Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt
  Android/build.gradle
Labels: Android

#53 [FE] Home 화면에 보여주는 데이터 수정 및 CSS 약간 수정됨
  FE/src/App.tsx
  FE/src/apis/home.ts
  FE/src/components/Input/index.tsx
  FE/src/constants/dummyData.js
  FE/src/interfaces/IMap.ts
  FE/src/mocks/handlers/index.js
  FE/src/pages/Home/Item/index.tsx
  FE/src/pages/Home/index.tsx
  FE/src/pages/Maps/Maps.stories.tsx
  FE/src/pages/Maps/Maps.style.ts
  FE/src/pages/Maps/index.tsx
Labels: FE, refactor

#54 refactor: Header 컴포넌트 새로운 디자인 시안처럼 수정, Input Component border 속성 추가, …
  FE/src/assets/images/logo.svg
  FE/src/assets/images/menu.svg
  FE/src/components/Input/Input.style.ts
  FE/src/components/Input/index.tsx
  FE/src/components/common/Header/Header.style.ts
  FE/src/components/common/Header/index.tsx
  FE/src/styles/theme.ts
Labels: FE, refactor

#55 [FE] Home 화면 UI 수정, Nav 컴포넌트 추가 => Type을 클릭하여 해당 타입에 맞는 지도를 가져오기
  FE/src/mocks/handlers/index.js
  FE/src/pages/Home/Home.style.ts
  FE/src/pages/Home/index.tsx
Labels: FE, refactor

#57 [FE] refactor - UI 수정 및 로딩 컴포넌트 색상 변경
  FE/src/assets/icons/map.svg
  FE/src/components/GridCards/GridCards.style.ts
  FE/src/components/common/LoadingSpinner/LoadingSpinner.style.ts
  FE/src/pages/MyPage/Item/index.tsx
  FE/src/pages/MyPage/MyPage.style.ts
  FE/src/pages/MyPage/index.tsx
Labels: FE, refactor

#58 [FE] refactor Maps 전체 UI 수정, maps 각 장소에 대한 정보 => 글로벌 모달창 띄우는 방식 변경, 카드 내 …
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/more.svg
  FE/src/pages/MyMap/Header/Header.style.ts
  FE/src/pages/MyMap/Header/index.tsx
  FE/src/pages/MyMap/Infos/Infos.style.ts
  FE/src/pages/MyMap/Infos/index.tsx
  FE/src/pages/MyMap/index.tsx
Labels: FE, refactor

#59 [FE] 로그인 기능 1차 완료. => 서버와 연동할때 url 연결 필요 및 CORS 해결필요
  FE/config/webpack.common.js
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Login/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/constants/url.ts
  FE/src/hooks/UseLogin.ts
  FE/src/hooks/useIsLoggedIn.ts
  FE/src/index.tsx
  FE/src/interfaces/IUser.ts
  FE/src/pages/Callback.tsx
  FE/src/pages/Home/index.tsx
  FE/src/pages/Verification.tsx
  FE/src/recoil/atoms/user.ts
  FE/src/utils/util.ts
  FE/yarn.lock
Labels: feature, FE

#60 🚧 feat: 네비게이션 네비게이션 외 영역 클릭 시 닫히도록 수정, 네비게이션 로그인시 보이는 화면과 비로그인시 화면 다르…
  FE/src/assets/icons/home.svg
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/myProfile.svg
  FE/src/components/Login/index.tsx
  FE/src/components/common/Header/Navigation/index.tsx
Labels: FE, refactor

#62 🚧 feat: 지도 생성 시 authority 옵션 추가, cookie 관련 코드 util로 관리
  FE/src/apis/mypage.ts
  FE/src/hooks/UseLogin.ts
  FE/src/pages/MyPage/Form/index.tsx
  FE/src/types/mypage.ts
  FE/src/utils/cookie.ts
Labels: feature, FE

#64 🚧 feat: home 더미데이터 authority 값 추가 및 CSS 깨지지 않게 수정
  FE/src/constants/dummyData.js
  FE/src/interfaces/IMap.ts
  FE/src/pages/Home/Item/Item.style.ts
  FE/src/pages/Home/Item/index.tsx
  FE/src/pages/Home/index.tsx
Labels: feature, FE

#69 [Android] feat: 지도 구현
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/squadmap/data/model/CategoryInfo.kt
  Android/app/src/main/java/com/example/squadmap/data/model/StoreInfo.kt
  Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt
  Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavMenu.kt
  Android/app/src/main/java/com/example/squadmap/ui/bottommenu/BottomNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/MapTypeChip.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/store/StoreList.kt
  Android/app/src/main/java/com/example/squadmap/ui/theme/Shape.kt
  Android/app/src/main/java/com/example/squadmap/ui/utils/Logger.kt
  Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt
  Android/build.gradle
  Android/gradle.properties
  Android/settings.gradle
Labels: Android

#71 🚧 feat: 카테고리 모달 UI 창 제작, 더미데이터 수정으로 인해 변경된 부분 다시 수정.
  FE/src/assets/icons/exclamation.svg
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/refresh.svg
  FE/src/constants/dummyData.js
  FE/src/pages/MyMap/Category/CategoryList.style.ts
  FE/src/pages/MyMap/Category/CategoryList.tsx
  FE/src/pages/MyMap/Category/CategoryModalInfo.style.ts
  FE/src/pages/MyMap/Category/CategoryModalInfo.tsx
  FE/src/pages/MyMap/Header/index.tsx
  FE/src/pages/MyMap/Infos/index.tsx
  FE/src/pages/MyPage/Item/index.tsx
Labels: feature, FE

#74 feat: github login 임시로 구현 아직 코드를 받아오지는 못함
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/squadmap/ui/login/LoginScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt
  Android/app/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
Labels: Android

#75 🚧 feat: 마이페이지 쪽 불필요한 문구 삭제 및 CSS 간격 조정, 카테고리 모달창에서의 배경색상 UI 수정
  FE/src/constants/colors.ts
  FE/src/constants/dummyData.js
  FE/src/pages/MyMap/Category/CategoryModalInfo.style.ts
  FE/src/pages/MyMap/Category/CategoryModalInfo.tsx
  FE/src/pages/MyPage/Item/Item.style.ts
  FE/src/pages/MyPage/Item/index.tsx
Labels: FE, refactor

#78 feat: 지도 마커 구현
  Android/app/build.gradle
  Android/app/src/main/java/com/example/squadmap/data/model/MapInfo.kt
  Android/app/src/main/java/com/example/squadmap/data/model/StoreInfo.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/store/StoreList.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt
Labels: Android

#80 feat: 지도 아래 가게 목록 구현
  Android/app/src/main/java/com/example/squadmap/common/Logger.kt
  Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMap.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/store/StoreList.kt
  Android/app/src/main/java/com/example/squadmap/ui/navigation/SquadMapNavGraph.kt
  Android/app/src/main/java/com/example/squadmap/ui/search/SquadMapIcons.kt
  Android/app/src/main/java/com/example/squadmap/ui/web/WebView.kt
Labels: Android

#81 🚧 feat: 장소 관련 페이지 검색 UI 완료, 더미데이터 출력
  FE/src/App.tsx
  FE/src/components/RecentSearch/RecentSearch.style.ts
  FE/src/components/RecentSearch/index.tsx
  FE/src/interfaces/ISearchPlace.ts
  FE/src/pages/MyMap/Header/Header.style.ts
  FE/src/pages/SearchMap/PlaceInfos/Infos.style.ts
  FE/src/pages/SearchMap/PlaceInfos/index.tsx
  FE/src/pages/SearchMap/SearchMap.style.ts
  FE/src/pages/SearchMap/SearchPlace/SearchPlace.style.ts
  FE/src/pages/SearchMap/SearchPlace/index.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/recoil/atoms/searchplace.ts
Labels: feature, FE

#86 [Android ] 네이버 맵 카카오 맵으로 변경
  Android/app/build.gradle
  Android/app/libs/libDaumMapAndroid.jar
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/squadmap/common/Constants.kt
  Android/app/src/main/java/com/example/squadmap/common/LifecycleExtension.kt
  Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSource.kt
  Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSourceImpl.kt
  Android/app/src/main/java/com/example/squadmap/data/dto/GeocodingResponse.kt
  Android/app/src/main/java/com/example/squadmap/data/dto/StoreSearchResultDTO.kt
  Android/app/src/main/java/com/example/squadmap/data/model/Coordinate.kt
  Android/app/src/main/java/com/example/squadmap/data/model/StoreInfo.kt
  Android/app/src/main/java/com/example/squadmap/data/model/StoreSearchData.kt
  Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepository.kt
  Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepositoryImpl.kt
  Android/app/src/main/java/com/example/squadmap/di/DataSourceModule.kt
  Android/app/src/main/java/com/example/squadmap/di/NetworkModule.kt
  Android/app/src/main/java/com/example/squadmap/di/RepositoryModule.kt
  Android/app/src/main/java/com/example/squadmap/network/GeocodingApi.kt
  Android/app/src/main/java/com/example/squadmap/network/StoreSearchApi.kt
  Android/app/src/main/java/com/example/squadmap/ui/Appbar.kt
  Android/app/src/main/java/com/example/squadmap/ui/MainActivity.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/AddStoreViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreDescriptionScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreSearchScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/SquadMapIcons.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/UiState.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/bottommenu/BottomNavMenu.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/bottommenu/BottomNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/navigation/SquadMapNavGraph.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/navigation/SquadMapNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/login/LoginScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMapScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/store/StoreListScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/search/SquadMapIcons.kt
  Android/app/src/main/java/com/example/squadmap/ui/theme/Color.kt
  Android/app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  Android/app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  Android/app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  Android/app/src/main/res/drawable/ic_add.xml
  Android/app/src/main/res/drawable/ic_github_logo_com.xml
  Android/app/src/main/res/drawable/ic_naver_logo.xml
  Android/app/src/main/res/xml/network_security_config.xml
  Android/build.gradle
  Android/gradle.properties
  Android/settings.gradle
Labels: Android

#88 feat: 검색 기능 카카오로 전환
  Android/app/build.gradle
  Android/app/src/main/java/com/example/squadmap/common/Constants.kt
  Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSource.kt
  Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSourceImpl.kt
  Android/app/src/main/java/com/example/squadmap/data/dto/GeocodingResponse.kt
  Android/app/src/main/java/com/example/squadmap/data/dto/StoreSearchResultDTO.kt
  Android/app/src/main/java/com/example/squadmap/data/model/StoreSearchData.kt
  Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepository.kt
  Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepositoryImpl.kt
  Android/app/src/main/java/com/example/squadmap/network/GeocodingApi.kt
  Android/app/src/main/java/com/example/squadmap/network/StoreSearchApi.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/AddStoreViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreSearchScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMapScreen.kt
Labels: Android

#90 feat: 장소 선택 후 다음으로 넘어가기 구현
  Android/app/src/main/java/com/example/squadmap/network/GeocodingApi.kt
  Android/app/src/main/java/com/example/squadmap/network/StoreSearchApi.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/AddStoreViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreDescriptionScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreSearchScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/navigation/SquadMapNavigation.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMapScreen.kt
Labels: Android

#92 🚧 [FE] Kakao Map API 를 활용하여 Marker, InfoWindow 기능 완료.
  FE/config/webpack.common.js
  FE/package.json
  FE/public/index.html
  FE/public/mockServiceWorker.js
  FE/src/components/KaKaoMap/index.tsx
  FE/src/constants/dummyData.js
  FE/src/interfaces/ISearchPlace.ts
  FE/src/pages/MyMap/Header/index.tsx
  FE/src/pages/MyMap/Infos/index.tsx
  FE/src/pages/MyMap/index.tsx
  FE/src/pages/SearchMap/PlaceInfos/Infos.style.ts
  FE/src/pages/SearchMap/PlaceInfos/index.tsx
  FE/src/pages/SearchMap/SearchPlace/index.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/styles/map.css
  FE/src/types/map.ts
  FE/yarn.lock
Labels: feature, FE, refactor

#94 [Android] feat: 장소 검색 페이징 구현
  Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSource.kt
  Android/app/src/main/java/com/example/squadmap/data/datasource/StoreSearchDataSourceImpl.kt
  Android/app/src/main/java/com/example/squadmap/data/dto/StoreSearchResultDTO.kt
  Android/app/src/main/java/com/example/squadmap/data/model/Coordinate.kt
  Android/app/src/main/java/com/example/squadmap/data/model/MapInfo.kt
  Android/app/src/main/java/com/example/squadmap/data/model/ResultStore.kt
  Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepository.kt
  Android/app/src/main/java/com/example/squadmap/data/repository/StoreSearchRepositoryImpl.kt
  Android/app/src/main/java/com/example/squadmap/network/StoreSearchApi.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/AddStoreViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreDescriptionScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/addstore/StoreSearchScreen.kt
  Android/app/src/main/java/com/example/squadmap/ui/common/navigation/SquadMapNavGraph.kt
  Android/app/src/main/java/com/example/squadmap/ui/home/HomeViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/MapViewModel.kt
  Android/app/src/main/java/com/example/squadmap/ui/map/StoreMapScreen.kt
Labels: Android
