Repository squad-map/squad-map-project, pull requests merged in 2023-01, with the labels that each got.

#170 ♻️ FE: API URL 수정 & 응답데이터 수정
  FE/src/apis/category.ts
  FE/src/apis/group.ts
  FE/src/apis/home.ts
  FE/src/apis/mypage.ts
  FE/src/apis/place.ts
  FE/src/apis/user.ts
Labels: refactor

#171 ♻️ FE : 데이터 및 컴포넌트 분리 리팩토링 진행.
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Authority/SearchForm/SearchForm.stories.tsx
  FE/src/components/Authority/SearchForm/SearchForm.style.ts
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Authority/SearchSubmitButton/SearchSubmitButton.style.ts
  FE/src/components/Authority/SearchSubmitButton/index.tsx
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/Form/Form.style.ts
  FE/src/components/Form/index.tsx
  FE/src/components/KaKaoMap/KakaoStaticMap.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/MyPage/Authority/index.tsx
  FE/src/components/NickName/NickName.stories.tsx
  FE/src/components/NickName/NickName.style.ts
  FE/src/components/NickName/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/constants/code.ts
  FE/src/hooks/UseLogin.ts
  FE/src/interfaces/IMyMap.ts
  FE/src/interfaces/IUser.ts
  FE/src/interfaces/group.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/Map/index.tsx
  FE/src/pages/MyPage/index.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/types/map.ts
Labels: refactor

#173 [BE] HOST 권한 변경 오류 및 그룹 지도 조회시 잘못된 지도 정보 응답 오류 수정
  BE/src/main/java/com/squadmap/core/group/domain/GroupMember.java
  BE/src/main/java/com/squadmap/core/group/domain/PermissionLevel.java
  BE/src/main/java/com/squadmap/core/group/infrastructure/GroupMemberRepository.java
  BE/src/test/java/com/squadmap/group/domain/GroupMemberTest.java
  BE/src/test/java/com/squadmap/group/integretion/GroupServiceTest.java
  BE/src/test/java/com/squadmap/map/domain/MapTest.java
  BE/src/test/java/com/squadmap/map/integration/MapServiceTest.java
Labels: bug, BE

#174 🚧, ♻️ : Category쪽 조회, 등록 완료 / 수정 및 삭제는 백엔드 method 405 error 나는중,
  FE/src/apis/category.ts
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/Category/ModifyCategforyModalInfo.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/SearchMap/PlaceInfos/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/components/common/Header/Navigation/Navigation.style.ts
  FE/src/components/common/Header/Navigation/index.tsx
  FE/src/constants/code.ts
  FE/src/pages/Map/index.tsx
  FE/src/utils/util.ts
Labels: feature, FE

#175 ♻️ 지도 생성, 수정, 삭제시 응답 모달창 구현 완료
  FE/src/components/Form/Form.style.ts
  FE/src/components/Form/index.tsx
Labels: refactor

#177 ♻️ 카테고리 수정 후 맵 refetch 해오기, 변수명 수정
  FE/src/components/Category/ModifyCategforyModalInfo.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/ModalContent/index.tsx
  FE/src/constants/code.ts
  FE/src/pages/Map/index.tsx
Labels: refactor

#178 🚧 FE: 장소 조회 및 삭제 API 연동
  FE/src/apis/place.ts
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/trash.svg
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/Map/Infos/Infos.stories.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalUpdate/PlaceModalUpdate.stories.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/constants/code.ts
  FE/src/pages/Map/index.tsx
Labels: feature, FE, refactor

#179 🚧 FE: 댓글 기능 작업 진행중, 작성 부분 완료 => 작성 후 refetch 필요. 진행예정
  FE/src/apis/comment.ts
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/PlaceModalReview.stories.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/Map/PlaceModalReview/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/constants/code.ts
  FE/src/interfaces/Comments.ts
  FE/src/interfaces/Place.ts
Labels: feature, FE

#180 🚧 FE : 댓글 삭제 기능 구현.
  FE/src/apis/comment.ts
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/PlaceModalComment.stories.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/constants/code.ts
Labels: feature, FE

#181 ♻️ FE : API 사용되어지는 변수명 전체 수정
  FE/src/apis/category.ts
  FE/src/apis/comment.ts
  FE/src/apis/group.ts
  FE/src/apis/home.ts
  FE/src/apis/mypage.ts
  FE/src/apis/place.ts
  FE/src/apis/user.ts
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/Category/ModifyCategforyModalInfo.tsx
  FE/src/components/Form/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/MyPage/Item/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/types/category.ts
  FE/src/types/group.ts
  FE/src/types/map.ts
  FE/src/types/mypage.ts
Labels: refactor

#183 🚧 FE : 로그인 임시 처리 -> accessToken이 없다면 로그인 페이지롱 이동시키기
  FE/src/apis/category.ts
  FE/src/apis/comment.ts
  FE/src/apis/group.ts
  FE/src/apis/mypage.ts
  FE/src/apis/place.ts
  FE/src/apis/user.ts
  FE/src/pages/Verification.tsx
Labels: refactor

#185 ♻️ API 수정, msw로 API 테스팅해보기
  FE/.storybook/main.js
  FE/.yarn/install-state.gz
  FE/package.json
  FE/src/apis/category.ts
  FE/src/apis/group.ts
  FE/src/apis/mypage.ts
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Category/CategoryModalInfo.tsx
  FE/src/components/Map/Infos/Infos.stories.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/MyPage/Authority/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/constants/category.ts
  FE/src/constants/code.ts
  FE/src/constants/comment.ts
  FE/src/constants/dummyData.js
  FE/src/constants/group.ts
  FE/src/constants/login.ts
  FE/src/constants/mypage.ts
  FE/src/constants/place.ts
  FE/src/constants/url.ts
  FE/src/constants/user.ts
  FE/src/mocks/handlers/category.ts
  FE/src/mocks/handlers/comment.ts
  FE/src/mocks/handlers/group.ts
  FE/src/mocks/handlers/home.ts
  FE/src/mocks/handlers/index.js
  FE/src/mocks/handlers/index.ts
  FE/src/mocks/handlers/login.ts
  FE/src/mocks/handlers/mymap.js
  FE/src/mocks/handlers/mypage.js
  FE/src/mocks/handlers/mypage.ts
  FE/src/mocks/handlers/place.ts
  FE/src/mocks/handlers/user.ts
  FE/yarn.lock
Labels: refactor, test

#186 ♻️ FE: API 2번 이상 호출되는 현상 수정 / 오류 수정
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Form/index.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalUpdate/PlaceModalUpdate.stories.tsx
  FE/src/components/MyPage/Authority/index.tsx
  FE/src/components/SearchMap/PlaceInfos/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/components/common/LoadingSpinner/index.tsx
  FE/src/constants/category.ts
  FE/src/constants/login.ts
  FE/src/constants/mypage.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/MyPage/index.tsx
  FE/src/pages/SearchMap/index.tsx
Labels: feature, FE, refactor, test

#188 🚧 FE : Home 화면 검색기능 / 무한스크롤링 기능 구현 완료
  FE/package.json
  FE/src/apis/home.ts
  FE/src/apis/mypage.ts
  FE/src/constants/mypage.ts
  FE/src/hooks/query/useAllMaps.tsx
  FE/src/hooks/query/useGroupMaps.tsx
  FE/src/pages/Home/index.tsx
  FE/src/tailwind/index.css
  FE/tailwind.config.js
  FE/yarn.lock
Labels: feature, FE

#189 Fe feature/patch comment
  FE/src/apis/comment.ts
  FE/src/apis/place.ts
  FE/src/assets/icons/commentEdit.svg
  FE/src/assets/icons/index.ts
  FE/src/components/Authority/GroupInfo/GroupInfo.stories.tsx
  FE/src/components/Map/Comment/CreateComment.stories.tsx
  FE/src/components/Map/Comment/CreateComment.tsx
  FE/src/components/Map/Comment/PatchCommentList.stories.tsx
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Comment/PatchCommentModal.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/index.tsx
Labels: feature, FE, refactor

#191 ♻️ FE-refactor 최근검색어 컴포넌트 기능 수정 / 장소 생성시 팝업 기능 추가
  FE/src/components/Category/ModifyCategoryModalInfo.tsx
  FE/src/components/Form/index.tsx
  FE/src/components/RecentSearch/RecentSearch.stories.tsx
  FE/src/components/RecentSearch/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/components/SearchMap/SearchPlace/index.tsx
  FE/src/constants/code.ts
  FE/src/recoil/atoms/searchplace.ts
Labels: feature, FE, refactor

#198 FE branch merge to main
  FE/config/webpack.prod.js
Labels: feature, FE, refactor

#199 ♻️ FE : msw 환경 dev로 다시 바꾸기
  FE/src/index.tsx
Labels: FE, refactor

#203 ♻️ FE/fix : 로딩 처리 데이터 없을때 처리 수정
  FE/src/components/Map/Header/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/MyPage/Authority/index.tsx
  FE/src/components/SearchMap/PlaceInfos/index.tsx
  FE/src/constants/mypage.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/Map/index.tsx
  FE/src/pages/MyPage/index.tsx
  FE/src/pages/SearchMap/index.tsx
Labels: FE, refactor

#204 [BE] logback 설정
  BE/.gitignore
  BE/Dockerfile
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/com/squadmap/core/category/application/CategoryServiceImpl.java
  BE/src/main/java/com/squadmap/core/category/application/dto/CategoryInfo.java
  BE/src/main/java/com/squadmap/core/category/domain/Category.java
  BE/src/main/java/com/squadmap/core/category/ui/CategoryController.java
  BE/src/main/java/com/squadmap/core/category/ui/dto/CategoryRequest.java
  BE/src/main/java/com/squadmap/core/group/application/GroupMemberServiceImpl.java
  BE/src/main/java/com/squadmap/core/group/ui/GroupMemberController.java
  BE/src/main/resources/application-performance.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/bulk-data.sql
  BE/src/main/resources/logback-spring.xml
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/com/squadmap/category/acceptance/CategoryAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java
  BE/src/test/resources/application-test.yml
Labels: BE

#206 ♻️ FE: 헤더 &카드내 프로필 이미지 추가
  FE/src/components/Item/index.tsx
  FE/src/components/KaKaoMap/KakaoStaticMap.tsx
  FE/src/components/KaKaoMap/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/constants/mypage.ts
Labels: refactor

#208 ♻️ FE : 카카오 맵 리렌더링 되기전 useEffect 사용하는 문제 제거 후 리팩토링.
  FE/src/components/Map/Infos/index.tsx
Labels: FE, refactor

#209 FE branch merge to main
  FE/src/components/Map/Infos/index.tsx
Labels: FE

#211 ♻️ FE: Group Map Error 처리 수정
  FE/src/pages/Home/index.tsx
Labels: FE, refactor

#212 🚧 FE: 오류사항 제보 문구 작성
  FE/src/components/ReportError/index.tsx
Labels: feature, FE

#214 [BE] 배포 flow 작성 및 로그 전략 구성
  .github/workflows/be-deploy.yml
  BE/.gitignore
  BE/Dockerfile
  BE/build.gradle
  BE/src/docs/asciidoc/index.adoc
  BE/src/main/java/com/squadmap/core/category/application/CategoryServiceImpl.java
  BE/src/main/java/com/squadmap/core/category/application/dto/CategoryInfo.java
  BE/src/main/java/com/squadmap/core/category/domain/Category.java
  BE/src/main/java/com/squadmap/core/category/ui/CategoryController.java
  BE/src/main/java/com/squadmap/core/category/ui/dto/CategoryRequest.java
  BE/src/main/java/com/squadmap/core/group/application/GroupMemberServiceImpl.java
  BE/src/main/java/com/squadmap/core/group/ui/GroupMemberController.java
  BE/src/main/resources/application-performance.yml
  BE/src/main/resources/application.yml
  BE/src/main/resources/bulk-data.sql
  BE/src/main/resources/logback-spring.xml
  BE/src/main/resources/static/docs/index.html
  BE/src/test/java/com/squadmap/category/acceptance/CategoryAcceptanceTest.java
  BE/src/test/java/com/squadmap/category/integration/CategoryServiceTest.java
  BE/src/test/resources/application-test.yml
Labels: feature, BE

#216 FE refactor/datas merge to FE
  FE/src/components/Category/CreateCategoryModalInfo.stories.tsx
  FE/src/components/Category/CreateCategoryModalInfo.tsx
  FE/src/components/KaKaoMap/KakaoStaticMap.tsx
  FE/src/components/KaKaoMap/index.tsx
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/NickName/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/components/common/Card/Card.style.ts
  FE/src/components/common/Card/index.tsx
  FE/src/components/common/Navigation/index.tsx
  FE/src/constants/map.ts
  FE/src/constants/mypage.ts
  FE/src/constants/place.ts
  FE/src/hooks/query/useAllMaps.tsx
  FE/src/hooks/useLogin.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/Map/index.tsx
Labels: feature, FE, refactor

#221 ♻️ FE : 지도내에서 헤더 카테고리 클릭시 해당 카테고리 데이터만 오른쪽 Infos에 뿌려주기 / Map 에서 헤더 컴…
  FE/src/components/Map/BackButton/BackButton.tsx
  FE/src/components/Map/Categories/Categories.stories.tsx
  FE/src/components/Map/Categories/Categories.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/constants/mypage.ts
  FE/src/pages/Map/index.tsx
  FE/src/pages/SearchMap/SearchMap.stories.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/types/map.ts
Labels: feature, FE, refactor

#222 FE branch merge to main
  FE/src/components/KaKaoMap/index.tsx
  FE/src/components/Map/BackButton/BackButton.tsx
  FE/src/components/Map/Categories/Categories.stories.tsx
  FE/src/components/Map/Categories/Categories.tsx
  FE/src/components/Map/Header/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/SearchMap/PlaceInfos/index.tsx
  FE/src/components/SearchMap/SearchPlace/index.tsx
  FE/src/components/common/Card/index.tsx
  FE/src/constants/mypage.ts
  FE/src/pages/Home/index.tsx
  FE/src/pages/Map/index.tsx
  FE/src/pages/SearchMap/SearchMap.stories.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/types/map.ts
Labels: FE

#228 ♻️ FE : 카테고리 수정하고 refetch시키기, 삭제 기능은 여기에 있을 필요가 없어보여 삭제.
  FE/src/components/Category/CategoryColorForm.tsx
  FE/src/components/Category/ModifyCategoryModalInfo.tsx
Labels: FE, refactor

#229 ♻️ FE - refactor => 로그인 페이지 height 조정, 카테고리 추가 버튼 삭제, 장소 정보 받아오기 전까지 …
  FE/src/components/Login/index.tsx
  FE/src/components/Map/Categories/Categories.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/SearchMap/SearchPlace/index.tsx
Labels: FE, refactor

#230 ♻️ FE: Refetch 리팩토링
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Category/CategoryColorForm.tsx
  FE/src/components/Category/ModifyCategoryModalInfo.tsx
  FE/src/components/Map/Comment/CreateComment.tsx
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Comment/PatchCommentModal.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/MyPage/Authority/index.tsx
  FE/src/hooks/query/useGroupMaps.tsx
  FE/src/mocks/handlers/comment.ts
  FE/src/pages/Map/index.tsx
Labels: FE, refactor

#231 FE branch merge to main
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Category/CategoryColorForm.tsx
  FE/src/components/Category/ModifyCategoryModalInfo.tsx
  FE/src/components/Map/Comment/CreateComment.tsx
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Comment/PatchCommentModal.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/MyPage/Authority/index.tsx
  FE/src/hooks/query/useGroupMaps.tsx
  FE/src/mocks/handlers/comment.ts
  FE/src/pages/Map/index.tsx
Labels: FE, refactor

#232 ♻️ Modal 재사용 훅스로 빼기
  FE/src/components/Authority/GroupInfo/index.tsx
  FE/src/components/Authority/SearchForm/index.tsx
  FE/src/components/Category/CategoryColorForm.tsx
  FE/src/components/Category/CreateCategoryModalInfo.tsx
  FE/src/components/Form/index.tsx
  FE/src/components/Map/Categories/Categories.tsx
  FE/src/components/Map/Comment/CreateComment.tsx
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Comment/PatchCommentModal.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/NickName/index.tsx
  FE/src/components/SearchMap/SearchModalContent/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/LoadingSpinner/index.tsx
  FE/src/hooks/useModal.tsx
Labels: FE, refactor

#234 🚧 Jest Setting, 유닛, 기능 테스트 하나씩 해보기 => Form Component Test Code 작성, Cr…
  FE/.babelrc
  FE/jest.config.js
  FE/package.json
  FE/setupTests.js
  FE/src/components/Form/Form.test.tsx
  FE/src/components/Form/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/common/Button/Button.test.tsx
  FE/src/mocks/browsers/index.js
  FE/src/pages/MapForm/index.tsx
  FE/src/tests/map.test.tsx
  FE/src/tests/testing-libaray-utils.tsx
  FE/tsconfig.json
Labels: test

#235 🚧 Jest Setting, 유닛, 기능 테스트 하나씩 해보기 => Form Component Test Code 작성, Cr…
  FE/.babelrc
  FE/jest.config.js
  FE/package.json
  FE/setupTests.js
  FE/src/components/Form/Form.test.tsx
  FE/src/components/Form/index.tsx
  FE/src/components/Map/PlaceModalUpdate/index.tsx
  FE/src/components/common/Button/Button.test.tsx
  FE/src/mocks/browsers/index.js
  FE/src/pages/MapForm/index.tsx
  FE/src/tests/map.test.tsx
  FE/src/tests/testing-libaray-utils.tsx
  FE/tsconfig.json
Labels: test

#236 🛠 Jest Setting -> 브라우저와 노드 별로 MSW 받아오기.
  FE/.eslintrc.js
  FE/.storybook/preview.js
  FE/package.json
  FE/setupTests.js
  FE/src/index.tsx
  FE/src/mocks/browsers/server.js
  FE/src/mocks/browsers/testServer.js
  FE/tsconfig.json
  FE/yarn.lock
Labels: FE, test

#237 FE branch merge to main
  FE/.eslintrc.js
  FE/.storybook/preview.js
  FE/package.json
  FE/setupTests.js
  FE/src/index.tsx
  FE/src/mocks/browsers/server.js
  FE/src/mocks/browsers/testServer.js
  FE/tsconfig.json
  FE/yarn.lock
Labels: FE, test

#238 FE test/map category
  FE/jest.config.js
  FE/package.json
  FE/src/components/Category/CreateCategoryModalInfo.tsx
  FE/src/components/KaKaoMap/index.tsx
  FE/src/components/NickName/NickName.test.tsx
  FE/src/components/NickName/index.tsx
  FE/src/components/RecentSearch/RecentSearch.test.tsx
  FE/src/components/RecentSearch/index.tsx
  FE/src/components/SearchMap/SearchPlace/index.tsx
  FE/src/mocks/handlers/category.ts
  FE/src/mocks/handlers/mypage.ts
  FE/src/mocks/handlers/user.ts
  FE/src/pages/SearchMap/SearchMap.test.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/tests/category.test.tsx
  FE/src/tests/map.test.tsx
  FE/src/tests/testing-libaray-utils.tsx
Labels: FE, test

#239 FE branch merge main
  FE/jest.config.js
  FE/package.json
  FE/src/components/Category/CreateCategoryModalInfo.tsx
  FE/src/components/KaKaoMap/index.tsx
  FE/src/components/NickName/NickName.test.tsx
  FE/src/components/NickName/index.tsx
  FE/src/components/RecentSearch/RecentSearch.test.tsx
  FE/src/components/RecentSearch/index.tsx
  FE/src/components/SearchMap/SearchPlace/index.tsx
  FE/src/mocks/handlers/category.ts
  FE/src/mocks/handlers/mypage.ts
  FE/src/mocks/handlers/user.ts
  FE/src/pages/SearchMap/SearchMap.test.tsx
  FE/src/pages/SearchMap/index.tsx
  FE/src/tests/category.test.tsx
  FE/src/tests/map.test.tsx
  FE/src/tests/testing-libaray-utils.tsx
Labels: FE, test

#240 🛠 Jest: css파일 못불러오는 부분 수정, 테스트 코드 환경에서 queryClient를 불러오면서 돔을 App 컴포넌트…
  FE/jest.config.js
  FE/package.json
  FE/src/index.tsx
  FE/src/mocks/handlers/place.ts
  FE/src/pages/SearchMap/SearchMap.test.tsx
  FE/src/tests/place.test.tsx
  FE/src/tests/testing-libaray-utils.tsx
Labels: FE, test

#241 🛠 Jest: css파일 못불러오는 부분 수정, 테스트 코드 환경에서 queryClient를 불러오면서 돔을 App 컴포넌트…
  FE/jest.config.js
  FE/package.json
  FE/src/index.tsx
  FE/src/mocks/handlers/place.ts
  FE/src/pages/SearchMap/SearchMap.test.tsx
  FE/src/tests/place.test.tsx
  FE/src/tests/testing-libaray-utils.tsx
Labels: FE, test

#242 ♻️ 장소 + 댓글 팝업 컴포넌트 수정 -> 장소 이야기 보여주기 + 댓글 을 작성한 닉네임과 이미지 노출
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/common/GlobalModal/index.tsx
  FE/src/constants/comment.ts
  FE/src/constants/place.ts
Labels: FE, refactor

#243 ♻️ 장소 + 댓글 팝업 컴포넌트 수정 -> 장소 이야기 보여주기 + 댓글 을 작성한 닉네임과 이미지 노출
  FE/src/components/Map/Comment/PatchCommentList.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/Map/PlaceModalComment/index.tsx
  FE/src/components/common/GlobalModal/index.tsx
  FE/src/constants/comment.ts
  FE/src/constants/place.ts
Labels: FE, refactor

#244 ♻️ 카테고리 클릭 시 카테고리 데이터만, 모든 지도 버튼 추가로 모든 지도 리스트도 볼 수 있게 수정, 닉네임 변경 관련 …
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/NickName/index.tsx
  FE/src/pages/Map/index.tsx
Labels: FE, refactor

#245 ♻️ 카테고리 클릭 시 카테고리 데이터만, 모든 지도 버튼 추가로 모든 지도 리스트도 볼 수 있게 수정, 닉네임 변경 관련 …
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/NickName/index.tsx
  FE/src/pages/Map/index.tsx
Labels: FE, refactor

#247 🚧 [FE] 카테고리 추가 및 수정 관련 기능 Map 페이지에서 바로 하도록 수정
  FE/src/components/Category/ModifyCategoryModalInfo.tsx
  FE/src/components/Map/CategoryManagement/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/common/Navigation/index.tsx
  FE/src/pages/Map/index.tsx
Labels: feature, FE, refactor

#248 🚧 [FE] 카테고리 추가 및 수정 관련 기능 Map 페이지에서 바로 하도록 수정
  FE/src/components/Category/ModifyCategoryModalInfo.tsx
  FE/src/components/Map/CategoryManagement/index.tsx
  FE/src/components/Map/Infos/index.tsx
  FE/src/components/common/Navigation/index.tsx
  FE/src/pages/Map/index.tsx
Labels: feature, FE

#249 🚧 FE - README 상세 요약 정리.
  README.md
Labels: documentation, FE

#252 🚧 FE : README FE 상세 정리
  README.md
Labels: documentation, FE
